### ISSUE TITLE
Intercept API: Expose more information

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser-plugins#15]
https://doc.qt.io/qt-5/qwebengineurlrequestinfo.html has some additional info (especially `ResourceType`) which we should probably expose.

**Comment by jgkamat** [comment]
This would be incredibly useful for blocking scripts, I think it would be OK to just define a special value when it can't be populated (eg: qtwebkit).

**Comment by The-Compiler** [comment]
I agree, using something like `ResourceType.Unavailable` (or the` Unknown` which QtWebEngine already has) seems fine. OTOH, maybe QtWebKit support is dropped by the time I get around to doing this :laughing:
