### ISSUE TITLE
Idea: Better Adblock Extension

### ISSUE THREAD

**Issue by taylo2allen** [qutebrowser/qutebrowser-plugins#20]
It would be nice to have a better adblock solution where you can whitelist and blacklist sites as well as blocking ads in the content of the site maybe a proxy.

**Comment by jgkamat** [comment]
taylo2allen writes:

> It would be nice to have a better adblock solution where you can whitelist 
> and blacklist sites as well as blocking ads in the content of the site maybe 
> a proxy.

The extension apis already exist for this, and I've already implemented an 
example. Not sure what 'maybe a proxy' means though.

**Comment by roosemberth** [comment]
> I've already implemented an example

@jgkamat Could you please share? :)

**Comment by mschilli87** [comment]
@roosemberth: https://gitlab.com/jgkamat/jblock

**Comment by jcmuller** [comment]
Is there any way we can work with [uBlock origin](https://github.com/gorhill/uBlock)?

**Comment by mschilli87** [comment]
@jcmuller: see https://github.com/qutebrowser/qutebrowser/issues/4832 :wink:

**Comment by lyiriyah** [comment]
will be fixed when https://github.com/qutebrowser/qutebrowser/pull/5317 is merged

**Comment by mschilli87** [comment]
@lyiriyah: While I agree https://github.com/qutebrowser/qutebrowser/pull/5317 will be a huge step forward, some more flexibilty in controlling what is blocked might still be left for an extension to implement.

**Comment by The-Compiler** [comment]
There already is an interceptor API - while it's not public yet (also see #13), I don't think there's anything left to do here (in terms of e.g. adding new APIs).
