### ISSUE TITLE
Possibility to import certificates

### ISSUE THREAD

**Issue by nepumuk-fs** [qutebrowser/qutebrowser-plugins#21]
* Like SSL certs, \*.crt files, \*.pem files, GPG/SSH keys, DFN-PKI, CA-certificates
* For using them during browsing, e. g. for GitHub, signing/verifying email (content)s

**Comment by The-Compiler** [comment]
I don't think this is qutebrowser's job. A browser typically only cares about client/server-side TLS certificates, right?
