### ISSUE TITLE
Handler for blocking JavaScript

### ISSUE THREAD

**Issue by nepumuk-fs** [qutebrowser/qutebrowser-plugins#22]
Possibility for specific sites, sessions or modes (e. g. private mode) to choose wich JS to block or JS from which site, resp.

**Comment by The-Compiler** [comment]
This is already implemented in qutebrowser. See https://github.com/qutebrowser/qutebrowser/issues/2314 for the private mode bit.

**Comment by jgkamat** [comment]
nepumuk-fs writes:

> JS from which site, resp.

By default it is a global js toggle. See http://gitlab.com/jgkamat/jmatrix for 
blocking scripts by source.

**Comment by The-Compiler** [comment]
> By default it is a global js toggle.

It's a per-page toggle, but allows scripts from any hosts while on a page where JS is allowed.
