### ISSUE TITLE
bitwarden extention

### ISSUE THREAD

**Issue by georgikoemdzhiev** [qutebrowser/qutebrowser-plugins#29]
Hello, 

It would be great to have a bitwarden extension available for the Qute browser users. It is one of the most popular password managers out there.

**Comment by The-Compiler** [comment]
See [qutebrowser/qute-bitwarden](https://github.com/qutebrowser/qutebrowser/blob/master/misc/userscripts/qute-bitwarden)

**Comment by georgikoemdzhiev** [comment]
> See [qutebrowser/qute-bitwarden](https://github.com/qutebrowser/qutebrowser/blob/master/misc/userscripts/qute-bitwarden)

Great, thank you!
