### ISSUE TITLE
Ublock Origin

### ISSUE THREAD

**Issue by SMproductive** [qutebrowser/qutebrowser-plugins#32]
https://github.com/gorhill/uBlock/

**Comment by The-Compiler** [comment]
qutebrowser has a built-in adblocker based on https://github.com/brave/adblock-rust already - given that WebExtensions support likely isn't going to happen without QtWebEngine adding support (see https://github.com/qutebrowser/qutebrowser/issues/30), neither is an 1:1 port of uBlock going to happen.
