### ISSUE TITLE
Perhaps getting support for Reddit Enhancement Suite?

### ISSUE THREAD

**Issue by ghost** [qutebrowser/qutebrowser-plugins#4]
The Reddit Enhancement Suite extension is the only extension still keeping me on Firefox. The other extensions are fulfilled by other programs like OpenVPN. So, if it is possible to port RES, it would be really nice.

**Comment by The-Compiler** [comment]
RES is implemented entirely in JavaScript, so there isn't much qutebrowser's extension API will be able to do there. However, https://github.com/honestbleeps/Reddit-Enhancement-Suite/pull/4694 would allow running it in qutebrowser via the existing GreaseMonkey support.
